"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { supabase } from "../lib/supabase";

const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0);
const daysAgo=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
type P={snapshot_date:string;sales_net:number;gross_profit:number};
type C={snapshot_date:string;running_costs:number;staff_costs:number;premises_costs:number;vehicle_costs:number;admin_costs:number;finance_costs:number};

export default function CostIntelligenceLayer(){
 const [active,setActive]=useState(false);const [host,setHost]=useState<HTMLElement|null>(null);const [profit,setProfit]=useState<P[]>([]);const [costs,setCosts]=useState<C[]>([]);
 useEffect(()=>{const sync=()=>{const h=document.querySelector(".main .topbar h1")?.textContent?.trim();setActive(h==="Finance");setHost(document.querySelector(".liveTabMount section") as HTMLElement|null)};sync();const o=new MutationObserver(sync);o.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>o.disconnect()},[]);
 useEffect(()=>{if(!active)return;const load=async()=>{const since=daysAgo(55);const [p,c]=await Promise.all([supabase.from("sage_profit_snapshots").select("snapshot_date,sales_net,gross_profit").gte("snapshot_date",since),supabase.from("sage_running_cost_snapshots").select("snapshot_date,running_costs,staff_costs,premises_costs,vehicle_costs,admin_costs,finance_costs").gte("snapshot_date",since)]);setProfit((p.data||[]) as P[]);setCosts((c.data||[]) as C[])};load();const id=setInterval(load,15*60*1000);return()=>clearInterval(id)},[active]);
 const d=useMemo(()=>{const cut=daysAgo(27),sum=(a:any[],k:string)=>a.reduce((s,x)=>s+(Number(x[k])||0),0),cur=costs.filter(x=>x.snapshot_date>=cut),prev=costs.filter(x=>x.snapshot_date<cut),sales=sum(profit.filter(x=>x.snapshot_date>=cut),"sales_net"),gp=sum(profit.filter(x=>x.snapshot_date>=cut),"gross_profit");const defs=[['Staff','staff_costs'],['Premises','premises_costs'],['Vehicles','vehicle_costs'],['Admin / tech','admin_costs'],['Finance','finance_costs']] as const;const cats=defs.map(([name,key])=>{const now=sum(cur,key),old=sum(prev,key),delta=now-old,change=old?delta/Math.abs(old)*100:0;return{name,now,old,delta,change,share:sales?now/sales*100:0}}).sort((a,b)=>b.delta-a.delta);const running=sum(cur,"running_costs"),oldRunning=sum(prev,"running_costs"),staff=cats.find(x=>x.name==='Staff')?.now||0,staffOld=cats.find(x=>x.name==='Staff')?.old||0,net=gp-running,save5=staff*.05,save10=staff*.10;return{sales,gp,net,running,oldRunning,cats,staff,staffOld,save5,save10,staffPct:sales?staff/sales*100:0,costPct:sales?running/sales*100:0}},[profit,costs]);
 if(!active||!host)return null;const rising=d.cats.filter(x=>x.delta>50),top=rising[0];
 return createPortal(<div className="costIntelligenceMount" style={{marginTop:18}}><div className="card" style={{borderWidth:2}}><div className="kpiLabel">COST INTELLIGENCE · WHERE TO INVESTIGATE FIRST</div><h3 style={{margin:"8px 0 4px"}}>{top?`${top.name} is the biggest cost increase versus the previous 28 days.`:"No major category increase is showing versus the previous 28 days."}</h3><div className="muted">Live Sage management view · compares the latest 28 days with the previous 28 days</div>
 <div className="kpiGrid" style={{marginTop:14}}><div className="card"><div className="kpiLabel">RUNNING COSTS</div><div className="kpiValue">{money(d.running)}</div><small>{d.sales?`${d.costPct.toFixed(1)}% of sales`:"—"} · {money(d.running-d.oldRunning)} vs previous period</small></div><div className="card"><div className="kpiLabel">STAFF COST</div><div className="kpiValue">{money(d.staff)}</div><small>{d.staffPct.toFixed(1)}% of sales · {money(d.staff-d.staffOld)} vs previous period</small></div><div className="card"><div className="kpiLabel">5% STAFF SAVING</div><div className="kpiValue">{money(d.save5)}</div><small>Would increase 28-day management profit to {money(d.net+d.save5)}</small></div><div className="card"><div className="kpiLabel">10% STAFF SAVING</div><div className="kpiValue">{money(d.save10)}</div><small>Would increase 28-day management profit to {money(d.net+d.save10)}</small></div></div>
 <div style={{overflowX:"auto",marginTop:16}}><table><thead><tr><th>Cost area</th><th>Current 28 days</th><th>Previous 28 days</th><th>£ movement</th><th>% movement</th><th>% of sales</th><th>Signal</th></tr></thead><tbody>{d.cats.map(x=><tr key={x.name}><td><b>{x.name}</b></td><td>{money(x.now)}</td><td>{money(x.old)}</td><td>{x.delta>=0?"+":""}{money(x.delta)}</td><td>{x.old?`${x.change>=0?"+":""}${x.change.toFixed(1)}%`:"—"}</td><td>{x.share.toFixed(1)}%</td><td>{x.delta>250?"Investigate":x.delta>50?"Watch":x.delta<-50?"Improving":"Stable"}</td></tr>)}</tbody></table></div>
 <div className="card" style={{marginTop:16}}><b>Stevie read:</b><div style={{marginTop:7}}>{top?`${top.name} has increased by ${money(top.delta)} (${top.old?`${top.change.toFixed(1)}%`:'new cost'}) versus the previous 28 days. Check this area first before making broad cuts.`:"Costs are broadly stable by category, so focus on efficiency rather than blanket cuts."}</div><div style={{marginTop:7}}>Staff currently consumes <b>{d.staffPct.toFixed(1)}% of sales</b>. A 5% reduction in staff cost is worth <b>{money(d.save5)}</b> every 28 days; 10% is worth <b>{money(d.save10)}</b>. These are scenarios, not a recommendation to cut headcount.</div></div></div></div>,host);
}
