"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0),today=()=>new Date().toISOString().slice(0,10);
export type CashCandidate={account_ref:string;name:string|null;telephone:string|null;balance:number;sales:number;previousSales:number;trend:number;inactive:number;status:string;reason:string};
type Kind="called"|"promised_payment"|"follow_up"|"resolved";
type Action={id:string;account_ref:string;customer_name:string|null;action_type:Kind;status:"open"|"promised"|"follow_up"|"resolved";note:string|null;promised_amount:number|null;due_date:string|null;created_at:string};
type Bridge={last_seen:string|null;last_customer_count:number|null;last_transaction_count:number|null};
function freshness(value:string|null){if(!value)return{label:"No Sage sync recorded",tone:"#b42318",stale:true};const mins=Math.floor((Date.now()-new Date(value).getTime())/60000);if(mins<60)return{label:`Sage updated ${Math.max(1,mins)} min ago`,tone:"#18794e",stale:false};const hours=Math.floor(mins/60);if(hours<24)return{label:`Sage updated ${hours} hr ago`,tone:hours>=2?"#9a6700":"#18794e",stale:hours>=2};return{label:`Sage updated ${Math.floor(hours/24)} day${hours>=48?"s":""} ago`,tone:"#b42318",stale:true}}
export default function CustomerActionQueue({customers}:{customers:CashCandidate[]}){
 const [actions,setActions]=useState<Action[]>([]),[bridge,setBridge]=useState<Bridge|null>(null),[selected,setSelected]=useState<CashCandidate|null>(null),[kind,setKind]=useState<Kind>("called"),[note,setNote]=useState(""),[amount,setAmount]=useState(""),[due,setDue]=useState(today()),[saving,setSaving]=useState(false),[error,setError]=useState(""),[showHistory,setShowHistory]=useState(false);
 const load=async()=>{const [a,b]=await Promise.all([supabase.from("customer_cash_actions").select("id,account_ref,customer_name,action_type,status,note,promised_amount,due_date,created_at").order("created_at",{ascending:false}).limit(500),supabase.from("sage_bridge_status").select("last_seen,last_customer_count,last_transaction_count").maybeSingle()]);if(a.error)setError("Action history is unavailable. The Blueprint 6.7 database update may still need applying.");else{setActions((a.data||[]) as Action[]);setError("")}if(!b.error)setBridge(b.data as Bridge|null)};
 useEffect(()=>{load();const id=setInterval(load,15*60*1000);return()=>clearInterval(id)},[]);
 const latest=useMemo(()=>{const m=new Map<string,Action>();actions.forEach(a=>{if(!m.has(a.account_ref))m.set(a.account_ref,a)});return m},[actions]);
 const ranked=useMemo(()=>customers.map(c=>{const recent=latest.get(c.account_ref),handledToday=Boolean(recent&&(recent.action_type==="called"||recent.action_type==="resolved")&&recent.created_at.slice(0,10)===today()),deferred=handledToday||Boolean(recent&&recent.status!=="resolved"&&recent.due_date&&recent.due_date>today()),dueNow=Boolean(recent&&recent.status!=="resolved"&&recent.due_date&&recent.due_date<=today()),cash=Math.max(0,Number(c.balance)||0),drop=c.previousSales>c.sales?c.previousSales-c.sales:0,score=(dueNow?200000:0)+(cash*100)+(cash>0&&drop>0?Math.min(drop,5000)*5:0)+(drop*2)+(c.inactive>=35?Math.min(c.inactive,120)*5:0)+(c.status==="Needs Attention"?1000:0);return{...c,cash,score,deferred,recent}}).filter(c=>c.score>0&&!c.deferred).sort((a,b)=>b.score-a.score).slice(0,8),[customers,latest]);
 const dueActions=useMemo(()=>actions.filter(a=>a.status!=="resolved"&&a.due_date&&a.due_date<=today()),[actions]),fresh=freshness(bridge?.last_seen||null);
 const choose=(c:CashCandidate,k:Kind)=>{setSelected(c);setKind(k);setNote("");setAmount(k==="promised_payment"?String(Math.round(Math.max(0,Number(c.balance)||0))):"");const d=new Date();d.setDate(d.getDate()+(k==="follow_up"?2:0));setDue(d.toISOString().slice(0,10));setError("")};
 const save=async()=>{if(!selected)return;if(kind==="promised_payment"&&(!Number(amount)||!due)){setError("Add the promised amount and payment date.");return}if(kind==="follow_up"&&!due){setError("Choose the follow-up date.");return}setSaving(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Your session has expired. Sign in again before saving.");setSaving(false);return}const status=kind==="promised_payment"?"promised":kind==="follow_up"?"follow_up":kind==="resolved"?"resolved":"open";const {error:e}=await supabase.from("customer_cash_actions").insert({user_id:user.id,account_ref:selected.account_ref,customer_name:selected.name,action_type:kind,status,note:note.trim()||null,promised_amount:kind==="promised_payment"?Number(amount):null,due_date:kind==="promised_payment"||kind==="follow_up"?due:null,completed_at:kind==="resolved"?new Date().toISOString():null});if(e)setError(`Could not save this action: ${e.message}`);else{setSelected(null);await load()}setSaving(false)};
 return <div className="card" style={{marginBottom:18,borderWidth:2}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><div className="kpiLabel">TODAY&apos;S CASH &amp; CUSTOMER ACTIONS</div><h2 style={{margin:"6px 0 3px"}}>Call these customers first</h2><div className="muted">Ranked by live Sage account balance, recoverable sales drop and time since last order.</div></div><div style={{textAlign:"right"}}><div style={{fontWeight:800,color:fresh.tone}}>● {fresh.label}</div><small>{bridge?`${bridge.last_customer_count||0} customers · ${bridge.last_transaction_count||0} transactions`:"Finance figures may not be current"}</small></div></div>{fresh.stale&&<div style={{marginTop:12,padding:12,borderRadius:10,background:"rgba(180,35,24,.1)",color:fresh.tone,fontWeight:700}}>Do not rely on the figures until the Sage bridge has synced again.</div>}{error&&<div role="alert" style={{marginTop:12,padding:12,borderRadius:10,background:"rgba(180,35,24,.1)",color:"#b42318"}}>{error}</div>}
 <div className="kpiGrid" style={{marginTop:14}}><div className="card"><div className="kpiLabel">CALLS TO MAKE</div><div className="kpiValue">{ranked.length}</div><small>Highest-value open actions</small></div><div className="card"><div className="kpiLabel">DUE TODAY</div><div className="kpiValue">{dueActions.length}</div><small>Promises and follow-ups due</small></div><div className="card"><div className="kpiLabel">SAGE BALANCE IN QUEUE</div><div className="kpiValue">{money(ranked.reduce((s,c)=>s+c.cash,0))}</div><small>Live account balances across today&apos;s ranked accounts</small></div></div>
 <div style={{display:"grid",gap:10,marginTop:16}}>{ranked.length===0?<div className="muted">No customer currently meets the attention rules.</div>:ranked.map((c,i)=><div key={c.account_ref} className="card" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,alignItems:"center"}}><div><div><b>{i+1}. {c.name||c.account_ref}</b> <span className="muted">{c.account_ref}</span></div><div style={{marginTop:5}}>{c.cash>0?<><b>{money(c.cash)} Sage balance</b> · </>:null}{c.reason}{c.previousSales>c.sales?` · ${money(c.previousSales-c.sales)} sales drop`:""}</div>{c.recent&&<small>Latest: {c.recent.action_type.replaceAll("_"," ")}{c.recent.due_date?` · due ${c.recent.due_date}`:""}</small>}</div><div style={{display:"flex",gap:7,flexWrap:"wrap",justifyContent:"flex-end"}}>{c.telephone&&<a className="btn" href={`tel:${c.telephone.replace(/\s/g,"")}`}>Call</a>}<button className="btn" onClick={()=>choose(c,"called")}>Called</button><button className="btn" onClick={()=>choose(c,"promised_payment")}>Promise</button><button className="btn" onClick={()=>choose(c,"follow_up")}>Follow up</button><button className="btn" onClick={()=>choose(c,"resolved")}>Resolved</button></div></div>)}</div>
 {selected&&<div className="card" style={{marginTop:14,background:"rgba(19,91,167,.06)"}}><h3 style={{marginTop:0,textTransform:"capitalize"}}>{kind.replaceAll("_"," ")} · {selected.name||selected.account_ref}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}>{kind==="promised_payment"&&<label>Promised amount (£)<input style={{display:"block",width:"100%",marginTop:5}} type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label>}{(kind==="promised_payment"||kind==="follow_up")&&<label>{kind==="promised_payment"?"Payment date":"Follow-up date"}<input style={{display:"block",width:"100%",marginTop:5}} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>}<label style={{gridColumn:"1/-1"}}>Note<input style={{display:"block",width:"100%",marginTop:5}} value={note} onChange={e=>setNote(e.target.value)} placeholder="What was agreed or what happens next?"/></label></div><div style={{display:"flex",gap:8,marginTop:12}}><button className="btn primary" disabled={saving} onClick={save}>{saving?"Saving…":"Save action"}</button><button className="btn" disabled={saving} onClick={()=>setSelected(null)}>Cancel</button></div></div>}
 <div style={{marginTop:14}}><button className="btn" onClick={()=>setShowHistory(v=>!v)}>{showHistory?"Hide":"Show"} action history</button>{showHistory&&<div style={{overflowX:"auto",marginTop:10}}><table><thead><tr><th>Date</th><th>Customer</th><th>Action</th><th>Amount</th><th>Due</th><th>Note</th></tr></thead><tbody>{actions.slice(0,50).map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleDateString("en-GB")}</td><td>{a.customer_name||a.account_ref}</td><td>{a.action_type.replaceAll("_"," ")}</td><td>{a.promised_amount?money(a.promised_amount):"—"}</td><td>{a.due_date||"—"}</td><td>{a.note||"—"}</td></tr>)}</tbody></table></div>}</div></div>
}
