"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { supabase } from "../lib/supabase";
import CustomerActionQueue, { type CashCandidate } from "./CustomerActionQueue";

const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0);
const pct=(n:number)=>`${(n||0).toFixed(1)}%`;
const isoDaysAgo=(days:number)=>{const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)};
const daysSince=(s:string)=>Math.max(0,Math.floor((Date.now()-new Date(`${s}T00:00:00`).getTime())/86400000));

type Profit={snapshot_date:string;sales_net:number;gross_profit:number;gross_profit_pct:number};
type Cost={snapshot_date:string;running_costs:number;staff_costs:number;premises_costs:number;vehicle_costs:number;admin_costs:number;finance_costs:number};
type Customer={account_ref:string;name:string|null;balance:number|null;credit_limit:number|null;telephone:string|null;email:string|null};
type Tran={account_ref:string;type:string;transaction_date:string;due_date:string|null;net_amount:number|null;outstanding:number|null};

export function LiveFinance(){
 const [profit,setProfit]=useState<Profit[]>([]);const [costs,setCosts]=useState<Cost[]>([]);const [debt,setDebt]=useState({outstanding:0,overdue:0});const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const start=isoDaysAgo(55);const [p,c,t]=await Promise.all([
  supabase.from("sage_profit_snapshots").select("snapshot_date,sales_net,gross_profit,gross_profit_pct").gte("snapshot_date",start).order("snapshot_date"),
  supabase.from("sage_running_cost_snapshots").select("snapshot_date,running_costs,staff_costs,premises_costs,vehicle_costs,admin_costs,finance_costs").gte("snapshot_date",start).order("snapshot_date"),
  supabase.from("sage_transactions").select("outstanding,due_date,type").gt("outstanding",0).limit(5000)
 ]);setProfit((p.data||[]) as Profit[]);setCosts((c.data||[]) as Cost[]);const today=new Date().toISOString().slice(0,10);let outstanding=0,overdue=0;(t.data||[]).forEach((x:any)=>{const v=Number(x.outstanding)||0;outstanding+=v;if(x.due_date&&x.due_date<today)overdue+=v});setDebt({outstanding,overdue});setLoading(false)};
 useEffect(()=>{load();const id=setInterval(load,15*60*1000);return()=>clearInterval(id)},[]);
 const data=useMemo(()=>{const cut=isoDaysAgo(27),prev=isoDaysAgo(55);const curP=profit.filter(x=>x.snapshot_date>=cut),oldP=profit.filter(x=>x.snapshot_date>=prev&&x.snapshot_date<cut),curC=costs.filter(x=>x.snapshot_date>=cut),oldC=costs.filter(x=>x.snapshot_date>=prev&&x.snapshot_date<cut);const sum=(a:any[],k:string)=>a.reduce((s,x)=>s+(Number(x[k])||0),0);const sales=sum(curP,"sales_net"),gp=sum(curP,"gross_profit"),running=sum(curC,"running_costs"),oldSales=sum(oldP,"sales_net"),oldRunning=sum(oldC,"running_costs");return{sales,gp,running,net:gp-running,margin:sales?gp/sales*100:0,oldSales,oldRunning,staff:sum(curC,"staff_costs"),premises:sum(curC,"premises_costs"),vehicles:sum(curC,"vehicle_costs"),admin:sum(curC,"admin_costs"),finance:sum(curC,"finance_costs")}},[profit,costs]);
 const change=(a:number,b:number)=>b?`${a>=b?"+":""}${((a-b)/Math.abs(b)*100).toFixed(1)}% vs previous 28 days`:"Previous period unavailable";
 return <section className="card" style={{marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><h2 style={{marginBottom:4}}>Live Sage Finance</h2><div className="muted">28-day management view · refreshes every 15 minutes</div></div><button className="btn" onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div><div className="kpiGrid" style={{marginTop:16}}><div className="card"><div className="kpiLabel">SALES</div><div className="kpiValue">{money(data.sales)}</div><small>{change(data.sales,data.oldSales)}</small></div><div className="card"><div className="kpiLabel">GROSS PROFIT</div><div className="kpiValue">{money(data.gp)}</div><small>{pct(data.margin)} margin · target 25%</small></div><div className="card"><div className="kpiLabel">RUNNING COSTS</div><div className="kpiValue">{money(data.running)}</div><small>{change(data.running,data.oldRunning)}</small></div><div className="card"><div className="kpiLabel">NET PROFIT</div><div className="kpiValue">{money(data.net)}</div><small>Management view · GP minus running costs</small></div><div className="card"><div className="kpiLabel">OUTSTANDING</div><div className="kpiValue">{money(debt.outstanding)}</div><small>Open Sage debtor transactions</small></div><div className="card"><div className="kpiLabel">OVERDUE</div><div className="kpiValue">{money(debt.overdue)}</div><small>Past due date</small></div></div><h3 style={{marginTop:20}}>Where the running costs are going</h3><div className="kpiGrid"><div className="card"><b>Staff</b><div>{money(data.staff)}</div></div><div className="card"><b>Premises</b><div>{money(data.premises)}</div></div><div className="card"><b>Vehicles</b><div>{money(data.vehicles)}</div></div><div className="card"><b>Admin / tech</b><div>{money(data.admin)}</div></div><div className="card"><b>Finance</b><div>{money(data.finance)}</div></div></div></section>
}

export function LiveCustomers(){
 const [customers,setCustomers]=useState<Customer[]>([]);const [trans,setTrans]=useState<Tran[]>([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [filter,setFilter]=useState<"all"|"attention"|"dropping"|"growing"|"overdue">("all");
 const load=async()=>{setLoading(true);const since=isoDaysAgo(89);let all:Tran[]=[];for(let from=0;from<10000;from+=1000){const {data}=await supabase.from("sage_transactions").select("account_ref,type,transaction_date,due_date,net_amount,outstanding").in("type",["SI","SC"]).gte("transaction_date",since).range(from,from+999);const page=(data||[]) as Tran[];all=all.concat(page);if(page.length<1000)break}const {data:c}=await supabase.from("sage_customers").select("account_ref,name,balance,credit_limit,telephone,email").order("name").limit(2000);setCustomers((c||[]) as Customer[]);setTrans(all);setLoading(false)};
 useEffect(()=>{load();const id=setInterval(load,15*60*1000);return()=>clearInterval(id)},[]);
 const allRows=useMemo(()=>{const today=new Date().toISOString().slice(0,10),curCut=isoDaysAgo(27),prevCut=isoDaysAgo(55),by=new Map<string,any>();trans.forEach(t=>{const x=by.get(t.account_ref)||{sales:0,previousSales:0,last:"",overdue:0};const sign=t.type==="SC"?-1:1;const value=sign*(Number(t.net_amount)||0);if(t.transaction_date>=curCut)x.sales+=value;else if(t.transaction_date>=prevCut)x.previousSales+=value;if(t.transaction_date>x.last)x.last=t.transaction_date;if((Number(t.outstanding)||0)>0&&t.due_date&&t.due_date<today)x.overdue+=Number(t.outstanding)||0;by.set(t.account_ref,x)});return customers.filter(c=>by.has(c.account_ref)).map(c=>{const x={...c,...by.get(c.account_ref)} as any;const trend=x.previousSales>0?((x.sales-x.previousSales)/x.previousSales)*100:(x.sales>0?100:0);const inactive=daysSince(x.last);const credit=Number(x.credit_limit)||0;const balance=Number(x.balance)||0;const creditRisk=credit>0&&balance>=credit*.85;let status="Healthy",reason="Trading normally";if(x.overdue>0||creditRisk||inactive>=35||(x.previousSales>=250&&trend<=-30)){status="Needs Attention";reason=x.overdue>0?`${money(x.overdue)} overdue`:creditRisk?"Close to credit limit":inactive>=35?`${inactive} days since last order`:`Sales down ${Math.abs(trend).toFixed(0)}%`;}else if(x.previousSales>=100&&trend>=20){status="Growing";reason=`Sales up ${trend.toFixed(0)}%`;}else if(x.previousSales>=100&&trend<=-15){status="Dropping";reason=`Sales down ${Math.abs(trend).toFixed(0)}%`;}return{...x,trend,inactive,status,reason}})},[customers,trans]);
 const insights=useMemo(()=>{const attention=allRows.filter((x:any)=>x.status==="Needs Attention"),dropping=allRows.filter((x:any)=>x.status==="Dropping"||x.reason?.startsWith("Sales down")),growing=allRows.filter((x:any)=>x.status==="Growing"),overdue=allRows.filter((x:any)=>x.overdue>0);const biggest=[...allRows].sort((a:any,b:any)=>b.sales-a.sales)[0];const biggestDrop=[...dropping].sort((a:any,b:any)=>a.trend-b.trend)[0];return{attention,dropping,growing,overdue,biggest,biggestDrop}},[allRows]);
 const rows=useMemo(()=>allRows.filter((c:any)=>`${c.account_ref} ${c.name||""}`.toLowerCase().includes(search.toLowerCase())).filter((c:any)=>filter==="all"||filter==="attention"&&c.status==="Needs Attention"||filter==="dropping"&&(c.status==="Dropping"||c.reason?.startsWith("Sales down"))||filter==="growing"&&c.status==="Growing"||filter==="overdue"&&c.overdue>0).sort((a:any,b:any)=>(a.status==="Needs Attention"?-1:0)-(b.status==="Needs Attention"?-1:0)||(b.overdue-a.overdue)||(b.sales-a.sales)),[allRows,search,filter]);
 const insightCard=(label:string,value:string,detail:string,onClick:()=>void)=><button className="card" onClick={onClick} style={{textAlign:"left",cursor:"pointer",width:"100%",color:"inherit"}}><div className="kpiLabel">{label}</div><div className="kpiValue" style={{fontSize:24}}>{value}</div><small>{detail}</small></button>;
 return <><CustomerActionQueue customers={allRows as CashCandidate[]}/><section className="card"><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{marginBottom:4}}>Live Customer Intelligence</h2><div className="muted">Sage activity · current 28 days compared with previous 28 days · active customers only</div></div><div style={{display:"flex",gap:8}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer or A/C…"/><button className="btn" onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div></div>
 <div className="kpiGrid" style={{marginTop:16}}>{insightCard("NEEDS ATTENTION",String(insights.attention.length),"Overdue, credit risk, lapsed or sharp sales drop",()=>setFilter("attention"))}{insightCard("DROPPING",String(insights.dropping.length),insights.biggestDrop?`${insights.biggestDrop.name||insights.biggestDrop.account_ref} · ${insights.biggestDrop.reason}`:"No material drops",()=>setFilter("dropping"))}{insightCard("GROWING",String(insights.growing.length),"20%+ growth vs previous 28 days",()=>setFilter("growing"))}{insightCard("OVERDUE",String(insights.overdue.length),`${money(insights.overdue.reduce((s:number,x:any)=>s+x.overdue,0))} overdue`,()=>setFilter("overdue"))}{insightCard("BIGGEST CUSTOMER",insights.biggest?money(insights.biggest.sales):"—",insights.biggest?.name||"No sales yet",()=>setFilter("all"))}</div>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className={`btn ${filter==="all"?"primary":""}`} onClick={()=>setFilter("all")}>All</button><button className={`btn ${filter==="attention"?"primary":""}`} onClick={()=>setFilter("attention")}>Needs Attention</button><button className={`btn ${filter==="dropping"?"primary":""}`} onClick={()=>setFilter("dropping")}>Dropping</button><button className={`btn ${filter==="growing"?"primary":""}`} onClick={()=>setFilter("growing")}>Growing</button><button className={`btn ${filter==="overdue"?"primary":""}`} onClick={()=>setFilter("overdue")}>Overdue</button></div>
 <div style={{overflowX:"auto",marginTop:16}}><table className="sageCustomerTable"><thead><tr><th>Status</th><th>A/C</th><th>Customer</th><th>28-day sales</th><th>Trend</th><th>Balance</th><th>Overdue</th><th>Last order</th><th>Insight</th><th>Telephone</th></tr></thead><tbody>{rows.map((c:any)=><tr key={c.account_ref}><td><b>{c.status}</b></td><td>{c.account_ref}</td><td><b>{c.name||"—"}</b></td><td>{money(c.sales)}</td><td>{c.previousSales>0?`${c.trend>=0?"+":""}${c.trend.toFixed(0)}%`:"New / no prior"}</td><td>{money(Number(c.balance)||0)}</td><td>{c.overdue>0?<b>{money(c.overdue)}</b>:"—"}</td><td>{c.last||"—"}</td><td>{c.reason}</td><td>{c.telephone||"—"}</td></tr>)}</tbody></table></div><div className="muted" style={{marginTop:10}}>Showing {rows.length} of {allRows.length} active customers · signals are management prompts, not automatic decisions.</div></section></>
}

export default function LiveFinanceCustomerTabs(){
 const [active,setActive]=useState<"Finance"|"Customers"|null>(null);const [target,setTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{const sync=()=>{const main=document.querySelector(".main") as HTMLElement|null;const heading=main?.querySelector(".topbar h1")?.textContent?.trim();setTarget(main);setActive(heading==="Finance"?"Finance":heading==="Customers"?"Customers":null)};sync();const observer=new MutationObserver(sync);observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!target)return;const children=Array.from(target.children) as HTMLElement[];children.forEach(el=>{if(el.classList.contains("topbar")||el.classList.contains("liveTabMount"))return;if(active){if(el.dataset.liveTabsPreviousDisplay===undefined)el.dataset.liveTabsPreviousDisplay=el.style.display||"";el.style.display="none"}else if(el.dataset.liveTabsPreviousDisplay!==undefined){el.style.display=el.dataset.liveTabsPreviousDisplay;delete el.dataset.liveTabsPreviousDisplay}});return()=>{children.forEach(el=>{if(el.dataset.liveTabsPreviousDisplay!==undefined){el.style.display=el.dataset.liveTabsPreviousDisplay;delete el.dataset.liveTabsPreviousDisplay}})}},[active,target]);
 if(!active||!target)return null;return createPortal(<div className="liveTabMount" style={{width:"100%"}}>{active==="Finance"?<LiveFinance/>:<LiveCustomers/>}</div>,target);
}
