"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { supabase } from "../lib/supabase";

const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(n||0);
const daysAgo=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};

type P={snapshot_date:string;sales_net:number;gross_profit:number};
type C={snapshot_date:string;running_costs:number};
type T={account_ref:string;type:string;transaction_date:string;due_date:string|null;net_amount:number|null;outstanding:number|null};
type Cust={account_ref:string;name:string|null;balance:number|null;credit_limit:number|null};

function InsightBox({children}:{children:React.ReactNode}){return <div className="card" style={{margin:"16px 0",borderWidth:2}}><div className="kpiLabel" style={{marginBottom:8}}>STEVIE INSIGHT · WHAT NEEDS YOUR ATTENTION</div>{children}</div>}

export default function StevieIntelligenceLayer(){
 const [active,setActive]=useState<"Finance"|"Customers"|null>(null);const [host,setHost]=useState<HTMLElement|null>(null);
 const [profit,setProfit]=useState<P[]>([]);const [cost,setCost]=useState<C[]>([]);const [trans,setTrans]=useState<T[]>([]);const [customers,setCustomers]=useState<Cust[]>([]);
 useEffect(()=>{const sync=()=>{const h=document.querySelector(".main .topbar h1")?.textContent?.trim();setActive(h==="Finance"?"Finance":h==="Customers"?"Customers":null);setHost(document.querySelector(".liveTabMount section") as HTMLElement|null)};sync();const o=new MutationObserver(sync);o.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>o.disconnect()},[]);
 useEffect(()=>{if(!active)return;const load=async()=>{const since=daysAgo(55);if(active==="Finance"){const [p,c]=await Promise.all([supabase.from("sage_profit_snapshots").select("snapshot_date,sales_net,gross_profit").gte("snapshot_date",since),supabase.from("sage_running_cost_snapshots").select("snapshot_date,running_costs").gte("snapshot_date",since)]);setProfit((p.data||[]) as P[]);setCost((c.data||[]) as C[])}else{let all:T[]=[];for(let from=0;from<10000;from+=1000){const {data}=await supabase.from("sage_transactions").select("account_ref,type,transaction_date,due_date,net_amount,outstanding").in("type",["SI","SC"]).gte("transaction_date",since).range(from,from+999);const page=(data||[]) as T[];all=all.concat(page);if(page.length<1000)break}const {data:c}=await supabase.from("sage_customers").select("account_ref,name,balance,credit_limit").limit(2000);setTrans(all);setCustomers((c||[]) as Cust[])}};load()},[active]);
 const finance=useMemo(()=>{const cut=daysAgo(27),sum=(a:any[],k:string)=>a.reduce((s,x)=>s+(Number(x[k])||0),0),cur=profit.filter(x=>x.snapshot_date>=cut),prev=profit.filter(x=>x.snapshot_date<cut),cc=cost.filter(x=>x.snapshot_date>=cut),pc=cost.filter(x=>x.snapshot_date<cut);const sales=sum(cur,"sales_net"),oldSales=sum(prev,"sales_net"),gp=sum(cur,"gross_profit"),running=sum(cc,"running_costs"),oldRunning=sum(pc,"running_costs"),margin=sales?gp/sales*100:0,targetGP=sales*.25,gap=Math.max(0,targetGP-gp),net=gp-running,netMargin=sales?net/sales*100:0,breakEven=margin>0?running/(margin/100):0;return{sales,oldSales,gp,running,oldRunning,margin,gap,net,netMargin,breakEven}},[profit,cost]);
 const customer=useMemo(()=>{const cut=daysAgo(27),by=new Map<string,any>();trans.forEach(t=>{const x=by.get(t.account_ref)||{cur:0,prev:0,overdue:0,last:""},v=(t.type==="SC"?-1:1)*(Number(t.net_amount)||0);if(t.transaction_date>=cut)x.cur+=v;else x.prev+=v;if(t.transaction_date>x.last)x.last=t.transaction_date;if((Number(t.outstanding)||0)>0&&t.due_date&&t.due_date<new Date().toISOString().slice(0,10))x.overdue+=Number(t.outstanding)||0;by.set(t.account_ref,x)});const rows=customers.filter(c=>by.has(c.account_ref)).map(c=>({...c,...by.get(c.account_ref)}));const drops=rows.filter((x:any)=>x.prev>=100&&x.cur<x.prev).map((x:any)=>({...x,lost:x.prev-x.cur,pct:(x.cur-x.prev)/x.prev*100})).sort((a:any,b:any)=>b.lost-a.lost),gains=rows.filter((x:any)=>x.prev>=100&&x.cur>x.prev).map((x:any)=>({...x,gain:x.cur-x.prev})).sort((a:any,b:any)=>b.gain-a.gain),lost=drops.reduce((s:any,x:any)=>s+x.lost,0),gained=gains.reduce((s:any,x:any)=>s+x.gain,0),overdue=rows.reduce((s:any,x:any)=>s+x.overdue,0);return{drops,gains,lost,gained,overdue,top:drops.slice(0,3)}},[trans,customers]);
 if(!active||!host)return null;
 const financeView=<InsightBox><div style={{fontSize:18,fontWeight:700,marginBottom:10}}>{finance.margin<25?`Margin is ${finance.margin.toFixed(1)}% — ${ (25-finance.margin).toFixed(1)} points below your 25% target.`:`Margin is at or above the 25% target.`}</div><div style={{display:"grid",gap:7}}><div>• <b>Margin opportunity:</b> {finance.gap>0?`${money(finance.gap)} extra GP would bring the last 28 days to 25%.`:"Target achieved."}</div><div>• <b>Sales movement:</b> {money(finance.sales-finance.oldSales)} vs previous 28 days ({finance.oldSales?`${((finance.sales-finance.oldSales)/Math.abs(finance.oldSales)*100).toFixed(1)}%`:"no comparison"}).</div><div>• <b>Cost movement:</b> {money(finance.running-finance.oldRunning)} vs previous 28 days.</div><div>• <b>Net management margin:</b> {finance.netMargin.toFixed(1)}% ({money(finance.net)}).</div><div>• <b>Estimated break-even sales:</b> {money(finance.breakEven)} per 28 days at the current GP margin.</div></div><div style={{marginTop:12,fontWeight:700}}>Best move: {finance.gap>0?"protect and improve gross margin first; every margin point flows directly into GP before overhead changes.":finance.running>finance.oldRunning?"margin is on target, so investigate the increase in running costs.":"protect current margin and focus on profitable sales growth."}</div></InsightBox>;
 const customerView=<InsightBox><div style={{fontSize:18,fontWeight:700,marginBottom:10}}>{customer.lost>customer.gained?`Declining accounts have lost ${money(customer.lost)} of 28-day sales versus the previous period.`:`Growth from improving accounts is currently outweighing customer declines.`}</div><div style={{display:"grid",gap:7}}><div>• <b>Sales lost from declining accounts:</b> {money(customer.lost)} across {customer.drops.length} customers.</div><div>• <b>Sales gained from growing accounts:</b> {money(customer.gained)} across {customer.gains.length} customers.</div><div>• <b>Net movement within those accounts:</b> {money(customer.gained-customer.lost)}.</div><div>• <b>Overdue exposure:</b> {money(customer.overdue)}.</div>{customer.top.length>0&&<div>• <b>Call first:</b> {customer.top.map((x:any)=>`${x.name||x.account_ref} (${money(x.lost)} lost)`).join(" · ")}</div>}</div><div style={{marginTop:12,fontWeight:700}}>Best move: {customer.top.length?`contact ${customer.top[0].name||customer.top[0].account_ref} first — it has the largest recoverable sales drop in the current comparison.`:"No meaningful declining account is showing in this comparison."}</div></InsightBox>;
 return createPortal(<div className="stevieIntelligenceMount">{active==="Finance"?financeView:customerView}</div>,host);
}
